### ISSUE TITLE
How can we match symbols across files in no-undef without ESM nor CJS ?

### ISSUE THREAD

**Issue by mathieulb** [selectnull/eslint-plugin-googleappsscript#9]
This project only lists globals to be ignored; it does not handle the fact that GAS has its own module system in which all **/*.js files in a library are treated as one module such that every function of every file is accessible from every other file. Users should be able to benefit from `no-undef`, so supposing that disabling it is out of the question, then I don't know how we're supposed to handle multi-files with eslint in a plain javascript project, no babel, no webpack, no tsc.

I don't see any `env` or `parserOptions` option of eslintrc for specifying this kind of unified scope, nor in rule `no-undef` itself. I tried `mkdir -p tmp; cat classe/*.js util/*.js test/*.js > tmp/cat.js; node node_modules/.bin/eslint tmp/cat.js` and it works except all line numbers are wrong, of course.

Is there some supposition that we should never use GAS without adding some ESM or CJS module system through something babel/webpack/tsc ? I don't see it documented anywhere...

**Comment by selectnull** [comment]
I don't have a good answer to your question as I haven't use GAS for anything more complex than a few sheet-bound functions for the past several years.

Do you have a solution?

**Comment by mathieulb** [comment]
Not sure. After some more hours on our project, I'd rather have it switched to TypeScript, but the GAS debugger refuses to show TypeScript code and use `.js.map` files; so, barring that, and wanting to preserve source filenames in the GAS debugger as well (such that Webpack would be a bad idea), we'd have to code our own package system using ({ ... ))() and a global variable for storing exports, but it couldn't be fully CJS-compatible because we can't control the order in which the modules are loaded. It doesn't really need to be loadable in Node, it only needs to make ESLint do the right thing, but if I modify the code so that ESLint does the right thing, it still has to run in GAS. I don't know yet how I'll make this happen... if I do.

**Comment by selectnull** [comment]
I'll close this issue since it's not actioable at this time. @mathieulb if you make it work, feel free to send a PR or open a new issue to discuss it.
